services:
  - type: web
    name: atish-chat-app-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGO_URI
        value: mongodb+srv://kallupatel2002_db_user:nHqqgZt1GQFj2KQ0@cluster0.qrzioxu.mongodb.net/chatapp?appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://atishchat.netlify.app

